### ISSUE TITLE
Oddajam svoj projekt

### ISSUE THREAD

**Issue by pavlanovak** [pavlanovak/APPR-2021-22#1]
Upam, da je ok in vse deluje.

**Comment by evadezelak** [comment]
Z oddajo projekta je vse uredu, poročilo se prevede. Projekt bo ocenjen v naslednjih dneh.

**Comment by katarinabrilej** [comment]
Ocena in komentar sta vpisana v spletni učilnici.

**Comment by pavlanovak** [comment]
Hvala!
